### ISSUE TITLE
Bounty proposal: Fill out questionnaire from consultant 3

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/card-issuance#11]
**Goal**

I cooperate with several professional consultants in international payments and card issuing.
This consultant 3 offered a provider that meets our requirements and serves companies registered in the BVI.
The questionnaire is requested by the provider.

**Actions**

Fill out the questionnaire. 

1. Bank Balance (planned balance) 

2. Annual Banking Volume 

3. Annual FX Volume & Annual Please-  estimate annual volume of FX required in your main operational currency, along with Same Currency 
Payment Volume 

4. Incoming Payments 

5. Outgoing Payments 

6. Transaction Frequency per month

7. Please provide detail of which jurisdictions your funds will be received in from and what types of company/individual

8. Flow of Funds

Please provide detail of whether your facility will receive/distribute payments in 1st Party (bank account in your 
 name), 2nd Party (inter-group transactions) or 3rd party (external entity) via your ECAP facility by marking the below:
 1st – 1st (Y/N) 
 1st – 2nd (Y/N) 
 1st – 3rd (Y/N)
 2nd – 1st (Y/N) 
 3rd – 1st (Y/N)
 3rd – 3rd (Y/N)

9. Please provide detail of the source of your funds, outlining how you have accumulated these monies and where they 
 are currently situated (current bank and location)

**Time estimate**

Minimum 2 days, maybe more.

**Comment by pavlovcik** [comment]
Skeptical of using middle men because we're going to overpay. I also think the bounty should only be for filling out the questionnaire.

**Comment by sergfeldman** [comment]
> Skeptical of using middle men because we're going to overpay.

@pavlovcik Please, validate how I understand your input:
- We will fill out this form and send to the consultant.
- We do not want to pay consultants any amount of reward even in case of successfully established partnership with a provider.

> I also think the bounty should only be for filling out the questionnaire.

Please, clarify what do you mean by this :)

**Comment by pavlovcik** [comment]
> Please, clarify what do you mean by this :)

> As a side note: I have a feeling that it only makes sense to make bounties on deliverables like the content for the submissions. The actual submission process itself, unless its on GitHub in the form of a pull request like with W3F, I think it's a bit awkward to prove.

https://github.com/ubiquity/business-development/issues/50#issuecomment-1628429907

**Comment by Hodlatoor** [comment]
My experience with this sort of payment middlemen companies is that it's best to go direct. And they are an anachronism from the '90s.  I know some shady companies like BPS which will take on merchant processing but the fees are exorbitant.

**Comment by sergfeldman** [comment]
The responses were prepared and sent to the consultant.
After the feedback, the answers were improved and sent to the payment provider.

I cannot agree with the skepticism about the interaction with consultants in this case, where each country and each provider has its own compliance specifics.
Since you are skeptical about interactions with consultants, this task may not be a bounty.

**Comment by pavlovcik** [comment]
Can you compile the q&a in a markdown document and associate it with this issue? This will allow the organization to be synchronized on this information.

**Comment by Hodlatoor** [comment]
@sergfeldman @pavlovcik anything needed from me on this one?

**Comment by sergfeldman** [comment]
> Can you compile the q&a in a markdown document and associate it with this issue? This will allow the organization to be synchronized on this information.

@pavlovcik The file is added via the PR in the .xlsx format as requested by the consultant.
Is this ok or is it necessary to create a markdown document?

**Comment by sergfeldman** [comment]
> @sergfeldman @pavlovcik anything needed from me on this one?

@Hodlatoor Thank you, nothing is needed for this task at the moment :)

**Comment by pavlovcik** [comment]
> > Can you compile the q&a in a markdown document and associate it with this issue? This will allow the organization to be synchronized on this information.
> 
> 
> 
> @pavlovcik The file is added via the PR in the .xlsx format as requested by the consultant.
> 
> Is this ok or is it necessary to create a markdown document?

Markdown if suitable for the content. 

.csv if it needs X and Y dimensions

**Comment by sergfeldman** [comment]
We received a refusal from the card issuing provider.
The announced reason is insufficient preparation for the card issuing program.

The consultant from herself added that one of the reasons may be insufficient for this provider transaction volume.

Since we are currently skeptical about consultants, I will pause the cooperation with this consultant.

**Comment by sergfeldman** [comment]
Thank you! Claimed
