### ISSUE TITLE
Bounty proposal: Compile answers for the 1st set of questions from Alchemy Pay

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/card-issuance#13]
### Intro

Alchemy Pay https://alchemypay.org/crypto-card is a known Web3 player. 
To proceed they asked some questions.

@pavlovcik please, review and approve this bounty.

### Goal
Compile answers for the 1st set of questions from Alchemy Pay.

### Activity
- Compile answers for the questions
1. Do you require any specialized solutions outside of the standard on/off ramping? (e.g. custom coin listing, custom blockchain, bespoke solutions, etc.)
2. What are some important regions or payment methods that you require?
3. What about the monthly transaction volume you are expecting after integration?
4. When are you looking to integrate?
5. The amounts you would like to release on the customer side?

### Time estimate
1 day

**Comment by pavlovcik** [comment]
To clarify these dont need a lot of research. Just use your best judgement to give them answers that sort of make sense with what we're doing. The main thing to realize is that these are screening questions. Give them the answers they wanna hear to get on the phone with them. The purpose of these activities are to build relationships with card issuers. 
We need those meetings set up. That's the goal; not giving them 100% accurate answers. We'll be able to move an order of magnitude faster without turning every one of these web forms into a full day project to ensure 100% accuracy.

**Comment by sergfeldman** [comment]
Studying the Alchemy Pay documentation and compiling relevant answers to these questions took about 1 day.
The answers were accepted by Alchemy Pay.
The call with them took place today, I'm waiting for the details of their proposal.

**Comment by sergfeldman** [comment]
I merged the PR and after that, the issue closed automatically.
For some reason, there is no payment permit.

**Comment by pavlovcik** [comment]
I'll try to generate a new one.

**Comment by sergfeldman** [comment]
Thank you, claimed
