### ISSUE TITLE
Fill out questionnaire 1 for Paymentology: Collect information

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/card-issuance#14]

**Comment by pavlovcik** [comment]
> Permit generation skipped since this issue didn't qualify as bounty

That is unexpected. I have to review the logs on my computer for why it says this.

**Comment by pavlovcik** [comment]
This is hard to do from my phone

**Comment by pavlovcik** [comment]
Looks like an edge case where there has been no updates from you in over a week since beginning the task (aside from the delivered work) and the bot won't let me keep you assigned as a consequence. Please follow up on this when the linked issue is completed.

**Comment by sergfeldman** [comment]
> Also if you leave a comment here to signal activity from you it might let me keep you assigned.

A comment: this task on the infornation collection was planned for 1 day but in reality took about 1 week because involved a BIN sponsors research.

**Comment by sergfeldman** [comment]
> #### Conversation Rewards
> ### [ **pavlovcik: [ CLAIM 9.3 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiOTMwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjQyODkwMjk5OTYyNjk0NDYyNDc1MTIxMzM1Njk0ODA1NDcyMzUyOTA1OTEzNDg4MTA5Nzg5ODUyODI4MjYwOTA2MzY3Nzk1NzA3MjIzIiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHg0MDA3Q0UyMDgzYzdGM0UxODA5N2FlQjNBMzliYjhlQzE0OWEzNDFkIiwicmVxdWVzdGVkQW1vdW50IjoiOTMwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4Zjg3Y2E0NTgzQzc5MjIxMmU1MjcyMGQxMjdFN0UwQTM4QjgxOGFEMSIsInNpZ25hdHVyZSI6IjB4NjI5YWM3MTk3MmFjYmNhN2VlMzJiNjQyN2M1Njk1MTQwMWI1NWEyNWE5YjM1MDJiMDc3M2UyNjg2ODcyNDc2YzU0YWM0MTQ4N2IyNTQzZGI2NmRiM2YxOWMwNzYxZmU3N2M4MmMwOGIyNTVkYzU2Y2ZkZTMwNjNkYjM5YzZiM2YxYiJ9&network=100)
> ### [ **sergfeldman: [ CLAIM 2.6 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMjYwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjQyODkwMjk5OTYyNjk0NDYyNDc1MTIxMzM1Njk0ODA1NDcyMzUyOTA1OTEzNDg4MTA5Nzg5ODUyODI4MjYwOTA2MzY3Nzk1NzA3MjIzIiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHgxNkIyNDMzYjlDRjVGRjg3ZEUwM2REYUVlYTYyN0M5MTA2RWUxMTdhIiwicmVxdWVzdGVkQW1vdW50IjoiMjYwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4Zjg3Y2E0NTgzQzc5MjIxMmU1MjcyMGQxMjdFN0UwQTM4QjgxOGFEMSIsInNpZ25hdHVyZSI6IjB4NWM4NmUyZWZhYTdlZmJiMjEyODY3ZmZiNWYzMjE0YzU1NjgzMDVkZWQyYTk2OTkzNDk2ZGU1ZDM2ZDZiZTJhNTQ3YmNkZTU2NTkzNDZkZDU3YmZmZmRmNzYxNzBkNzAxOWVlZGY0ZDZmNTc3YmExN2E4MTcyMTJkM2U3NjBkYjYxYyJ9&network=100)

@pavlovcik There is an error 
![Permit is not claimable](https://github.com/ubiquity/card-issuance/assets/15567379/e53f4f12-4732-4674-914a-84c29feed5f9)

**Comment by sergfeldman** [comment]
> Yes unfortunately it's a known issue that only one permit claim will work from each issue at the moment. We are working on a fix [here](https://github.com/ubiquity/ubiquibot/issues/686).

@sergfeldman Thank you for the info, will wait for the fix.

**Comment by sergfeldman** [comment]
Conversation Rewards is still THIS PERMIT IS NOT CLAIMABLE

**Comment by pavlovcik** [comment]
I think the next bot update is the best solution for that
