### ISSUE TITLE
Research card issuing by PST

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/card-issuance#19]
@pavlovcik please review

### Intro 
PST https://pst.net/ is one of the top providers of global cards focused on advertisement.
They issue global Visa virtual cards for advertising and personal purchases. 
The KYC process is lightweight. 

### Goal
Research card issuing by PST 

### Activity

- **PST: gather general information** 

Get information on the PST cards specifics and pricing, collect public information about their card issuing process (realize how they managed to issue global cards), find their public partners (BIN sponsors, etc), other valuable information.

Time estimate: minimum 1 day.
Risks - not all required information can be available publicly. 

- **PST: research white-label solution and other options for cooperation** 

Contact PST, clarify the ability for us to use their white label solution, if it is possible then get terms and access. 

Time estimate: minimum 1 day.
Risks - they will not reply or not approve us because our request might not be relevant to them.

**Comment by sergfeldman** [comment]
For future analysis: this task took 2 full days, as it was planned.

**Comment by sergfeldman** [comment]
> Permit generation skipped since this issue didn't qualify as bounty

@pavlovcik Can you please make this bounty claimable?

**Comment by sergfeldman** [comment]
@pavlovcik Thank you! 
Not enough funds now :)

![image](https://github.com/ubiquity/card-issuance/assets/15567379/8a1dba76-3b66-4f26-9219-c973a589c694)

**Comment by sergfeldman** [comment]
> However I just topped it up with 1000 WXDAI now. https://gnosisscan.io/tx/0x3360a3c230142f9833468031765f7f04266589fde6811eea51641e96a699bfe7

@pavlovcik Thank you again! 
I`ve successfully claimed 84 wxdai, but 300 xwdai permit is not claimable at the moment. 

![Permit is not claimable](https://github.com/ubiquity/card-issuance/assets/15567379/cb5eecf3-49db-455e-b84a-b0bcf8a94539)

**Comment by pavlovcik** [comment]
We can regenerate it when the permit nonce fix is rolled out. Apologies.

**Comment by sergfeldman** [comment]
Task Assignee Reward is still THIS PERMIT IS NOT CLAIMABLE
![Not claimable](https://github.com/ubiquity/card-issuance/assets/15567379/34e11d36-29cc-4a2d-b3c3-a83610e3d574)

**Comment by pavlovcik** [comment]
I'm reviewing my notifications. Perhaps manual payouts are needed if you have a lot of unclaimable rewards. I'll have to do it on my computer

**Comment by sergfeldman** [comment]
There are just 2 issues left where I'm not able to claim Task Assignee Reward
- https://github.com/ubiquity/card-issuance/issues/19 (this issue)
- https://github.com/ubiquity/research/issues/34
