### ISSUE TITLE
Bounty proposal: Receive 1 offer from a card issuance provider 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/card-issuance#25]
### Intro 

At the moment, I am negotiating with 2 card issuance providers which provide global card issuance services.

Paymentology
https://www.paymentology.com/platform/prepaid-and-debit-cards
https://www.paymentology.com/product/flex
https://www.paymentology.com/use-cases/digital-banks
https://www.paymentology.com/use-cases/high-performing-fintechs

Choise 
https://choise.com/card
https://vault.ist/ 

They are satisfied that Ubiquity 
- A crypto company
- Registered in the BVI

Identified risks
- Providers may not be satisfied with the small number of cards that Ubiquity needs at the beginning 
- Providers prices may be higher than our expectations

I expect to receive an offer from at least one of these 2 providers in October 2023.
Other providers are covered in separate tasks so an offer from another provider from these 2 will not be considered as a deliverable for this task.

@pavlovcik You [recommended](https://github.com/ubiquity/card-issuance/issues/6#issuecomment-1725186490) batching several bounties into one because it can be more efficient for approvals from you.
Please, review this bounty that combines negotiation with these 2 providers. 

### Goal 

Receive at least 1 official offer from any of these 2 card issuance providers

### Activity 

- Clarify our and their requirements
- Prepare for calls and read their documentation 
- Make calls with them
- Provide answers to the providers' questions
- Sign an NDA (with Choise)
And so on

### Time estimate 

It is extremely difficult to determine how much pure time it will take before receiving an offer.
At the moment I estimate the pure time spent for 1 provider at least 1 week.
2 providers mean a minimum of 2 weeks.

**Comment by pavlovcik** [comment]
Hmm weird it's not dynamically calculating based on the 2 week amount. 

Nothing works this week that's why I spent so much time personally working on the code to fix things lol

**Comment by pavlovcik** [comment]
Nice

**Comment by sergfeldman** [comment]
@pavlovcik The offers are confidential due to NDA. Please, do not share them outside Ubiquity.
- [Offer from Paymentology](https://drive.google.com/file/d/1RbeztdtgacVjg06O9fgzrKdMZ4NgfLr0/view?usp=drive_link)
- [Not final offer from Vault.ist](https://drive.google.com/file/d/1k88bMOQi8ZTKlvnNu9yOm51NjqH6BiJt/view?usp=drive_link)

**Comment by sergfeldman** [comment]
The draft of Vault.ist API reference https://choisecom.notion.site/Vault-API-Specification-4d2719b90070482bb788115beded1be5

**Comment by pavlovcik** [comment]
Based on what I read from your findings and this perplexity summary, I am more partial towards investing in working with Paymentology 

https://www.perplexity.ai/search/we-are-considering-Cqj7Uy4FRAm7fhkx4khs_Q?s=c

**Comment by sergfeldman** [comment]
I think that it is necessary to first get a more correct offer from Vault.ist which reflects the use of the API, and then make a decision on choosing one of these two providers.

Based on my personal observations, both providers Paymentology and Vault.ist are quite slow.
I continue to look for new providers that could become a strong strategic partner.

**Comment by pavlovcik** [comment]
Is there a public auditable deliverable that you can associate here via a pull request?

**Comment by sergfeldman** [comment]
> @pavlovcik The offers are confidential due to NDA. Please, do not share them outside Ubiquity.
> 
> * [Offer from Paymentology](https://drive.google.com/file/d/1RbeztdtgacVjg06O9fgzrKdMZ4NgfLr0/view?usp=drive_link)
> * [Not final offer from Vault.ist](https://drive.google.com/file/d/1k88bMOQi8ZTKlvnNu9yOm51NjqH6BiJt/view?usp=drive_link)

@pavlovcik As I mentioned, it is prohibited to make public those documents that are provided to us on NDA terms.
Access to these documents was limited, you have reviewed both documents and left comments.
If you wish, I can create a PR with links to these documents.

**Comment by pavlovcik** [comment]
Okay let's do that as a workaround for now.

**Comment by pavlovcik** [comment]
> Permit generation skipped since issue's bounty is higher than 1000
> 
> ###### If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory). Your endorsement means the world to us and helps us grow!
> ###### We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!

https://gnosisscan.io/tx/0x852eb3964b08b10f03fab900d31be23c3aac618a5c89a81b204cd137dc87320a

**Comment by sergfeldman** [comment]
Great thanks!
Claimed both Task Creator Reward and Conversation Reward
