### ISSUE TITLE
Bounty proposal: get one more card issuing option with API

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/card-issuance#26]
### Intro

At the moment, we have 1 offer on card issuing from Paymentology that has an API.
There are chances that we will get a relevant offer from Vault ist which is building its API. 
- https://github.com/ubiquity/card-issuance/issues/25

We need at least 1 more offer with API to compare prices and conditions. 
Also, I hope to find a more technology-driven provider with lower prices. 

Currently, I`m negotiating with providers that claim to have an API
Unlimit 
Striga
Mercuryo
Disrupttech 
Pst.net
And looking for more 

@pavlovcik Please, review this bounty.

### Goal 

Get one more card issuing option with API in addition to Paymentology and Vault ist. 

### Activity

- Clarify our and their requirements
- Prepare for calls and read their documentation
- Make calls with them
- Provide answers to the providers' questions
- Sign NDA
- Review draft offers
And so on

### Time estimate

Based on experience with Paymentology and Vault ist, it takes 4-6 weeks to get an offer from a provider. 
As I already started, I estimate the pure time spent for 1 new provider as 2-3 weeks.

**Comment by sergfeldman** [comment]
> Skipping `/start` since no time labels are set to calculate the timeline

Excuse me, I forgot that the bounty needs to be approved first

**Comment by sergfeldman** [comment]
Status on 11/13/2023
After the calls with Unlimit and Striga I got information that they require an entity in the EU. They are fine that we are a crypto startup with a small number of users. Both of them have API. 

They are interested in continuing communication.
Unlimit can at least offer an off-ramp service.
More negotiations need to be held to explore cooperation with Striga.

**Comment by sergfeldman** [comment]
Disrupttech API
https://cefi.disrupttech.io/about/api

**Comment by sergfeldman** [comment]
> Disrupttech API https://cefi.disrupttech.io/about/api

@pavlovcik Can you please review this API?

**Comment by sergfeldman** [comment]
Potentially, it will be possible to issue immediate cards with lightweight KYC.
An example of immediate cards with lightweight KYC is https://pst.net/ which I reviewed before.
This stream requires relatively long negotiations as a solution is planned to release by the end of 2023.

**Comment by pavlovcik** [comment]
> Disrupttech API
https://cefi.disrupttech.io/about/api

I took a quick look and I see some of the essential capabilities, such as the ability to view, and update a card balance. They require an email address for users which I am not really a fan of, but its fine. I also have an unsettled feeling of them being very Bitcoin oriented, with mentions of charging fees is sats etc. But this is minor. 

> https://pst.net/

I think that it is essential from a UX perspective to allow us to modify the user's balance on the card. Then, in the near future, we should be able to figure a flow that will automatically collect payment permits on behalf of users, and topping up their card balance) making the "earning" process seamless.

Do prepaid cards allow this? If so, then this can be a practical solution.

I do not fully understand the technical differences as they relate to end-user experience between prepaid, debit, and credit cards. But it surely appears that there are different levels of requirements with these (pre-paid apparently being the most lax for rules, while credit is the most difficult to issue.)

**Comment by sergfeldman** [comment]
Establishing contact with providers and obtaining offers is a non-standard and sometimes not straightforward task.
Each provider has its own flow of interaction with potential partners, as well as its own opportunities and risks.
Since we are talking about new providers with which we have no experience yet, it is extremely difficult to correctly predict the time spent.

**Time spent on experience with Paymentology and Vault ist:**

- The total time spent with Paymentology was more than 200 hours, including preparation and performing of about 10 meetings, filling out their forms, signing documents, extensive research of BIN sponsors, studying their documentation, answering questions, and so on.

- Total time spent with Vault ist was more than 80 hours, including preparing and conducting 6 calls, studying their documentation and their parent company documentation, trying to reduce prices for us using their referral program, and so on.

**The providers I talk to in the scope of this task have already led to unexpected time spending**

- For example, Mercuryo is creating a service for issuing prepaid cards, access to which will be without a setup fee, which is beneficial for us.
They claim that the early access group consists of top-level companies like Trust Wallet. The possibility of including us in this early access group is currently being discussed. One of the important things that Mercuryo was interested in was for me to share knowledge about all the providers I had studied. This can significantly save their efforts on competitor research. At one of the meetings, I gave them a brief review and will give more information if they progress with an offer for us.

**Sometimes an unexpected time spent is necessary simply to communicate with a provider**

- For example, Disrupttech more or less only responds in a specific messenger. This messenger has some restrictions that prevented me from using my phone number. I had to communicate with support for several hours to create an account that I could use.

I did not include in the estimate for this task time spent waiting for answers from providers, and also significant unexpected time spent.

**Comment by pavlovcik** [comment]
> One of the important things that Mercuryo was interested in was for me to share knowledge about all the providers I had studied. This can significantly save their efforts on competitor research.

Very cool.

**Comment by sergfeldman** [comment]
PST White Label is offered only for teams and businesses from 200K cards or with a card turnover of 1M USD per year. 

If we want to test not white-label card issuing via API then the subscription starts from 179 USD per month. 
https://pst.net/private 
https://app.pst.net/app/settings/api

**Comment by sergfeldman** [comment]
> Disrupttech API https://cefi.disrupttech.io/about/api

Disrupttech terms are not attractive
https://drive.google.com/file/d/1hhveSolBz-Jmt6CeZDX621-C6UUi3F8u/view

**Comment by pavlovcik** [comment]
> > Disrupttech API https://cefi.disrupttech.io/about/api
> 
> Disrupttech [terms](https://drive.google.com/file/d/1hhveSolBz-Jmt6CeZDX621-C6UUi3F8u/view) are not attractive for us.

Insane how greedy card issuers are.

**Comment by sergfeldman** [comment]
Vault ist added the API info to the [offer](https://drive.google.com/file/d/1iJS1rF-ZAKmCk7cfK8AV6Q_Regybugb6/view)

**Comment by Hodlatoor** [comment]
Hi Ser-
I would definitely suggest negotiating the onboarding and ongoing / minimum
fees as those can become prohibitive rather quickly especially in the early
stages When there is not a lot of volume / users. I think there is quite a
bit of room to negotiate down on most of their proposed numbers.

**Comment by sergfeldman** [comment]
@Hodlatoor Thank you for the input!
I've already tried to reduce the Vault ist fees, even explored using their referral program to decrease our costs. 
I will try again.

**Comment by sergfeldman** [comment]
Per information obtained on the calls, the initial setup costs with Unlimit will be about 100K, so there is no point in continuing communication for now.

**Comment by pavlovcik** [comment]
Due to costs, do you think it makes sense to focus on launching with (reloadable) prepaid cards?

**Comment by Hodlatoor** [comment]
It's important to have a bridge to real world utility. as long as the costs
are not prohibitive and can be swallowed I think it can be considered a
significant milestone.

**Comment by sergfeldman** [comment]
As far as I know, we have long-term plans to develop a Metaverse Bank.
To implement these plans, we will need a partner with the appropriate licenses and services. 
Additionally, partnering with a well-known provider can be beneficial for getting series A funding.

For the initial launch of cards, I am focused on finding an option with the lowest cost.
If I don’t find an acceptable option, then we should be ready for compromises, such as prepaid/gift cards.

**Comment by sergfeldman** [comment]
API https://doc-api.hyperpay.io/en/
SDK https://doc-sdk.hyperpay.io/en/
https://hyperpayhelp.zendesk.com/hc/en-us/articles/360001107536-User-Guide-for-HyperPay-Download

**Comment by sergfeldman** [comment]
The term "Metaverse bank" can be an issue in the future, because it meets the high-risk definition in the financial industry:
>Any activity involving the use of shell banks (entities that have no physical existence in the country in which it is incorporated and licensed) or **banks with no physical presence in any country that are not licensed by any banking authority**

**Comment by pavlovcik** [comment]
I think again, just check if we can manipulate the card balance

**Comment by sergfeldman** [comment]
@pavlovcik **pst.net Support confirmed that the following operations can be performed via their API triggered by our platform:**
- Issue a card for a new user of our platform
- Top up the balance of a card
- Read the balance of a card

It is not possible to review API references before purchasing a Private subscription.
The Support replied that the API documentation is available only after activation of the appropriate subscription.
I know that the API documentation was available for review previously. 

API access lifetime costs 500 USD.
For free API access, we need at least a Private Medium plan 
The first month is 149 USD (regular is 269 USD per month)
- 50 cards per month 
- 4% deposit fee (for the majority of the cards)
https://app.pst.net/app/subscription/promo

**As for other providers**
- We can try to issue free cards from https://combo.cards/
There is a 3% deposit fee
It will allow us to test the top-up flow but not the card issuing flow. 

- There are still some meetings and contacts already planned with other providers.

**Comment by pavlovcik** [comment]
> The Support replied that the API documentation is available only after activation of the appropriate subscription.

Seems very sketchy.

> https://combo.cards/

They have a lot of typos on their website which also seems pretty sketchy. Check out their KYC/AML policy regarding the Unity States of America https://combo.cards/privacy/

I think my primary concern with these types of businesses is that they are intended for a team to give spending cards to team members. I think this all runs through the business KYC. Although this may be appropriate for a prototype, we certainly would not be able to assume responsibility of every user of our platform. They should probably need to KYC.

**Comment by sergfeldman** [comment]
@0x4007 Hey, it is not enough funds in the wallet.
https://github.com/ubiquity/pay.ubq.fi/commit/bf5ca41
This is relevant for the rest of the rewards including https://github.com/ubiquity/card-issuance/issues/39
![1](https://github.com/ubiquity/card-issuance/assets/15567379/f1a2ade9-17ac-41e9-b732-f6b22fe4fdcd)

**Comment by 0x4007** [comment]
> @0x4007 Hey, it is not enough funds in the wallet.

I just topped the wallet up
