### ISSUE TITLE
Bounty proposal: integrate Reloadly API

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/card-issuance#34]
### Reloadly documentation

https://developers.reloadly.com/gift-cards/introduction Learn how to integrate Reloadly’s digital Gift Card API into your applications
https://docs.reloadly.com/gift-cards API description 
https://www.youtube.com/playlist?list=PLHScUwVHI4TAV03VEtSWyiAp5IkIiBKSp Quick guide to get started with Reloadly’s API
https://www.youtube.com/c/Reloadly
https://github.com/Reloadly
https://join.slack.com/t/reloadly-developers/shared_invite/zt-qflikche-fwiFA5Sxtst2mXzvJBPO3w Reloadly developers

### Available prepaid cards 

![Visa](https://github.com/ubiquity/card-issuance/assets/15567379/5483ec7f-b5e4-4b39-92ff-2e324d29513b)

![MasterCard](https://github.com/ubiquity/card-issuance/assets/15567379/64dc51b9-bb97-467f-8730-10b999438663)

### Top-up in crypto

![Crypto top-up](https://github.com/ubiquity/card-issuance/assets/15567379/055d711b-c33b-48a6-9576-af15398c4f4d)

### Access

https://dashboard.reloadly.com/
To get access to the Ubiquity account in the Reloadly admin panel, please contact @sergfeldman
You will need to use 2FA with Google Authenticator. 

Access to the API is [here](https://drive.google.com/drive/folders/1u2_Hdeg1vxWhaYmP0uhDXbArAGQUUnso)

### API setup 

We should set up static IPs for requesting the Reloadly API
https://dashboard.reloadly.com/security

Note from the Support
>Please don't forget to whitelist your IPs to remove restriction on sales amount. Currently, it is set to $100 and automatically will be removed when you add IPs.

![Whitelist IP](https://github.com/ubiquity/card-issuance/assets/15567379/c33bc198-f86b-44d7-89bf-434a7b97befd)

**Comment by 0x4007** [comment]
> reloadly expenses: 50$ (recharged reloadly with 50$)

https://gnosisscan.io/tx/0x44a612815d59bcfa353428301d43b0cf0f432f08ec772e4d8c42b72c1c964114

**Comment by sergfeldman** [comment]
@0x4007 I topped up the Reloadly account with 25 USD from my card.

You were going to think about compensating the activity that can't be reflected on GitHub - providing accesses to developers, cards activating and testing, researching the issues and getting help from Reloadly support.
In the absence of base pay such compensation is critical.

> This isn't auditable. The communications are to happen on GitHub under the project it's associated with so that information flows transparently through the organization, and so that the work is automatically compensated for when the project is complete.
This shouldn't be news because we have been using this system for a couple of years now.
I understand a lot of this involves credentials so we can consider an exception, but will require some more thought.

**Comment by EresDev** [comment]
> To calculate my reward for this issue, I am just using quick word count of my comments here + its PR relative to one of my previously completed issue and using the relative conversation rate.
> 
> So, here is something that I should be paid using this formula. Issue resolution: 1600$ conversation reward: 700$ reloadly expenses: 50$ (recharged reloadly with 50$) total: 1600 + 700 + 50 = 2350$
> 
> Please note that I am flexible to look into any other you think is better to calculate.

I was looking into why my guess of 700$ conversation reward was so off and I saw that the ubiquibot didn't count the comments in the pull request of this issue. Probably because the PR is in a different repository. 

Interestingly, my calculation of just counting the words worked nicely. Because for this issue without its pull request comments, my calculatino was 298$, and the bot counted it 287$. Very close. 

However, my calculation will still be off for about 150 to 200 because I also counted the PR body and the bot will exclude that I think.

**Comment by sergfeldman** [comment]
>I understand a lot of this involves credentials so we can consider an exception, but will require some more thought.

@0x4007 Hi, you promised earlier ^ to think and decide on compensation.
Can you please 
- Compensate my costs for replenishing the Reloadly account with 25 USD from my card. These funds were used for testing, including purchases performed by you in Korea.
- Additionally compensate for my support of the Reloadly integration, because a large part of the activity was not reflected in the GitHub comments to this task and was not compensated earlier.

**Comment by 0x4007** [comment]
> > I understand a lot of this involves credentials so we can consider an exception, but will require some more thought.
> 
> @0x4007 Hi, you promised earlier ^ to think and decide on compensation. Can you please
> 
> * Compensate my costs for replenishing the Reloadly account with 25 USD from my card. These funds were used for testing, including purchases performed by you in Korea.

https://gnosisscan.io/tx/0xf07eb7e9a569c92b5a2b4f9bb9e43b678b7adc31e9a6c3844b4d8821853ff3e2

> * Additionally compensate for my support of the Reloadly integration, because a large part of the activity was not reflected in the GitHub comments to this task and was not compensated earlier.

Base pay is designed to cover odds and ends like this.

**Comment by sergfeldman** [comment]
>https://gnosisscan.io/tx/0xf07eb7e9a569c92b5a2b4f9bb9e43b678b7adc31e9a6c3844b4d8821853ff3e2

@0x4007 Thank you.

>Base pay is designed to cover odds and ends like this.

This question arose because my base pay was stopped at the beginning of April 2024.
@0x4007 Later you compensated me for 1 month of base pay, meaning the base pay was paid until the beginning of May 2024.

This Reloadly integration task was completed in mid-June 2024.
This means that from the beginning of May 2024 until this task was completed in mid-June 2024, I was not paid any base pay.
